'use client';

import React, { useState } from 'react';
import AdminShell from '@/components/layout/AdminShell';
import { useLanguage } from '@/context/LanguageContext';
import {
  Calculator,
  CheckCircle2,
  Compass,
  Waves,
  Award,
  Crown,
  Sparkles,
  Zap,
  ArrowRight,
  ShieldCheck,
  TrendingUp,
  Coins,
} from 'lucide-react';
import CustomSelect from '@/components/ui/Select';

export default function AdminMembershipsPage() {
  const { t, isEn } = useLanguage();
  const [simulationPoints, setSimulationPoints] = useState(150);
  const [simL1Tier, setSimL1Tier] = useState('active_member');
  const [simL2Tier, setSimL2Tier] = useState('ambassador');

  const TIERS = [
    {
      id: 'member',
      name: isEn ? 'Member' : 'Miembro',
      tag: isEn ? 'Base Rank' : 'Rango Inicial',
      subtitle: isEn ? 'Initial level upon registration' : 'Nivel inicial al registrarse',
      icon: Compass,
      bgGradient: 'from-white to-slate-50/80',
      border: 'border-slate-200 hover:border-slate-400',
      iconBg: 'bg-slate-100 text-slate-700 ring-2 ring-slate-200',
      badgeStyle: 'bg-slate-100 text-slate-800 border-slate-300',
      maxReferralLevel: 0,
      rates: { 1: '0%', 2: '0%' },
      qualification: isEn ? 'Account registration completed.' : 'Registro de cuenta completado.',
      perks: isEn
        ? [
            'Access to travel offers catalog',
            'Personal referral code to invite friends',
            'Accumulates prospect network pending activation',
          ]
        : [
            'Acceso al catálogo de ofertas de viajes',
            'Código de referido personal para invitar amigos',
            'Acumula red de prospectos en espera de activación',
          ],
    },
    {
      id: 'active_member',
      name: isEn ? 'Active Member' : 'Miembro Activo',
      tag: isEn ? '1st Purchase' : '1ra Compra',
      subtitle: isEn ? 'First direct commission tier' : 'Primer nivel de comisión directa',
      icon: Waves,
      bgGradient: 'from-white to-emerald-50/50',
      border: 'border-emerald-200 hover:border-emerald-400',
      iconBg: 'bg-emerald-100 text-emerald-700 ring-2 ring-emerald-200',
      badgeStyle: 'bg-emerald-100 text-emerald-800 border-emerald-300',
      maxReferralLevel: 1,
      rates: { 1: '100%', 2: '0%' },
      qualification: isEn ? 'Make at least 1 travel package purchase.' : 'Realizar al menos 1 compra de paquete de viaje.',
      perks: isEn
        ? [
            'Earns 100% of base points on direct referral purchases (L1)',
            'Real-time visibility and statistics of Level 1 network',
            'Redemption of points for travel credit or vouchers',
          ]
        : [
            'Gana el 100% de los puntos base en compras de referidos directos (N1)',
            'Visibilidad y estadísticas en tiempo real de su Nivel 1',
            'Redención de puntos por crédito de viaje o vouchers',
          ],
    },
    {
      id: 'ambassador',
      name: isEn ? 'Ambassador' : 'Embajador',
      tag: isEn ? '2-Tier Leader' : 'Líder 2 Niveles',
      subtitle: isEn ? 'Dual-tier compensation level' : 'Doble nivel de compensación',
      icon: Award,
      bgGradient: 'from-white to-sky-50/60',
      border: 'border-sky-200 hover:border-sky-400',
      iconBg: 'bg-sky-100 text-sky-700 ring-2 ring-sky-200',
      badgeStyle: 'bg-sky-100 text-sky-800 border-sky-300',
      maxReferralLevel: 2,
      rates: { 1: '100%', 2: '50%' },
      qualification: isEn ? 'Maintain active referrals and continuous travel bookings.' : 'Mantener referidos activos y volumen continuo de viajes.',
      perks: isEn
        ? [
            '100% of points generated by Level 1 (Directs)',
            '50% of points generated by Level 2 (Indirect referrals)',
            'Full multi-tier network analytics access',
            'Priority on redemption requests and VIP deals',
          ]
        : [
            '100% de puntos generados por Nivel 1 (Directos)',
            '50% de puntos generados por Nivel 2 (Referidos indirectos)',
            'Acceso al panel analítico de red multinivel completa',
            'Prioridad en solicitudes de redención y ofertas VIP',
          ],
    },
    {
      id: 'elite_ambassador',
      name: isEn ? 'Elite Ambassador' : 'Embajador Élite',
      tag: isEn ? 'Top VIP Master' : 'Rango VIP Máster',
      subtitle: isEn ? 'Maximum leadership rank in the Club' : 'Rango máximo de liderazgo en el Club',
      icon: Crown,
      isDark: true,
      bgGradient: 'from-[#1C1009] via-[#150B06] to-[#0A0503] text-white',
      border: 'border-gold-400/80 hover:border-gold-300 shadow-lg shadow-gold-500/15',
      iconBg: 'bg-gradient-to-tr from-gold-500 to-amber-300 text-navy-950 ring-2 ring-gold-400/40',
      badgeStyle: 'bg-gradient-to-r from-gold-400 via-amber-300 to-gold-400 text-navy-950 border-gold-300 font-black',
      maxReferralLevel: 2,
      rates: { 1: '100%', 2: '50%' },
      qualification: isEn ? 'Outstanding network leadership and administrative assignment.' : 'Liderazgo de red destacada y asignación administrativa.',
      perks: isEn
        ? [
            '100% Level 1 + 50% Level 2 commissions',
            '24/7 dedicated personal travel concierge',
            'Access to wholesale rates and VIP room upgrades',
            'Quarterly performance bonuses and incentives',
          ]
        : [
            '100% comisiones Nivel 1 + 50% comisiones Nivel 2',
            'Atención personalizada de conserjería de viajes 24/7',
            'Acceso a tarifas mayoristas y upgrades exclusivos',
            'Recompensas e incentivos por metas trimestrales',
          ],
    },
  ];

  const getTierRate = (tierId, level) => {
    if (level === 1) {
      return tierId === 'member' ? 0 : 1.0;
    }
    if (level === 2) {
      return tierId === 'ambassador' || tierId === 'elite_ambassador' ? 0.5 : 0;
    }
    return 0;
  };

  const l1Earned = Math.round(simulationPoints * getTierRate(simL1Tier, 1));
  const l2Earned = Math.round(simulationPoints * getTierRate(simL2Tier, 2));

  return (
    <AdminShell
      title={t('memberships.title', 'Estructura de Membresías & Comisiones')}
      subtitle={t('memberships.subtitle', 'Reglas oficiales del club, niveles de referidos y simulador interactivo de liquidación')}
    >
      {/* 4 Ultra-Luxury Tiers Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {TIERS.map((tier) => {
          const Icon = tier.icon;
          const isDark = tier.isDark;

          return (
            <div
              key={tier.id}
              className={`relative rounded-3xl p-6 border-2 transition-all duration-300 hover:shadow-2xl hover:-translate-y-1.5 flex flex-col justify-between overflow-hidden group ${
                isDark
                  ? 'bg-gradient-to-b from-[#1C1009] via-[#150B06] to-[#0A0503] text-white border-gold-400/80 shadow-[0_8px_30px_-5px_rgba(212,160,23,0.3)]'
                  : `bg-gradient-to-b ${tier.bgGradient} ${tier.border} shadow-sm`
              }`}
            >
              {/* Background ambient lighting */}
              {isDark ? (
                <>
                  <div className="absolute top-0 right-0 w-36 h-36 bg-gold-400/15 rounded-full blur-2xl pointer-events-none -mr-8 -mt-8 group-hover:scale-150 transition-transform duration-700"></div>
                  <div className="absolute -right-4 -bottom-4 w-32 h-32 text-gold-400/[0.06] pointer-events-none group-hover:scale-110 transition-transform">
                    <Crown className="w-full h-full" />
                  </div>
                </>
              ) : (
                <div className="absolute -right-4 -bottom-4 w-32 h-32 opacity-[0.04] group-hover:opacity-[0.08] group-hover:scale-110 transition-all pointer-events-none">
                  <Icon className="w-full h-full" />
                </div>
              )}

              <div className="relative">
                {/* Header */}
                <div className="flex items-center justify-between gap-2 mb-4">
                  <div className={`w-11 h-11 rounded-2xl flex items-center justify-center shadow-md ${tier.iconBg}`}>
                    <Icon className="w-5 h-5" />
                  </div>
                  <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-wider border shadow-xs ${tier.badgeStyle}`}>
                    {tier.tag}
                  </span>
                </div>

                <h3 className={`text-xl font-serif font-black ${isDark ? 'text-transparent bg-clip-text bg-gradient-to-r from-gold-200 via-gold-300 to-amber-100' : 'text-navy-950'}`}>
                  {tier.name}
                </h3>
                <p className={`text-xs font-medium mt-1 mb-4 ${isDark ? 'text-sand-300/80' : 'text-slate-500'}`}>
                  {tier.subtitle}
                </p>

                {/* Commission Rates Matrix Box */}
                <div className={`p-4 rounded-2xl border mb-5 space-y-2 text-xs backdrop-blur-xs ${
                  isDark
                    ? 'bg-white/5 border-gold-500/30'
                    : 'bg-white/80 border-slate-200/80 shadow-xs'
                }`}>
                  <div className="flex justify-between items-center">
                    <span className={isDark ? 'text-sand-300' : 'text-slate-600'}>
                      {t('memberships.networkLevels', 'Niveles de Red:')}
                    </span>
                    <span className={`font-black font-mono px-2 py-0.5 rounded-md ${
                      isDark ? 'bg-gold-500/20 text-gold-300 border border-gold-500/40' : 'bg-slate-100 text-navy-950'
                    }`}>
                      {tier.maxReferralLevel} {isEn ? 'Level(s)' : 'Nivel(es)'}
                    </span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className={isDark ? 'text-sand-300' : 'text-slate-600'}>
                      {t('memberships.commissionN1', 'Comisión N1 (Directo):')}
                    </span>
                    <span className={`font-black font-mono px-2 py-0.5 rounded-md ${
                      tier.rates[1] !== '0%'
                        ? isDark
                          ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                          : 'bg-emerald-100 text-emerald-800'
                        : isDark ? 'text-sand-400' : 'text-slate-400'
                    }`}>
                      {tier.rates[1]}
                    </span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className={isDark ? 'text-sand-300' : 'text-slate-600'}>
                      {t('memberships.commissionN2', 'Comisión N2 (Indirecto):')}
                    </span>
                    <span className={`font-black font-mono px-2 py-0.5 rounded-md ${
                      tier.rates[2] !== '0%'
                        ? isDark
                          ? 'bg-sky-500/20 text-sky-300 border border-sky-500/40'
                          : 'bg-sky-100 text-sky-800'
                        : isDark ? 'text-sand-400' : 'text-slate-400'
                    }`}>
                      {tier.rates[2]}
                    </span>
                  </div>
                </div>

                {/* Benefits List */}
                <div className="space-y-2.5">
                  <p className={`text-[10px] font-extrabold uppercase tracking-widest ${isDark ? 'text-gold-400' : 'text-slate-400'}`}>
                    {t('memberships.benefits', 'Beneficios Clave:')}
                  </p>
                  <ul className="space-y-2 text-xs">
                    {tier.perks.map((p, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <CheckCircle2 className={`w-4 h-4 shrink-0 mt-0.5 ${isDark ? 'text-gold-400' : 'text-emerald-600'}`} />
                        <span className={isDark ? 'text-sand-200 font-medium' : 'text-slate-700 font-medium'}>{p}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Qualification footer */}
              <div className={`relative mt-6 pt-4 border-t text-xs ${
                isDark ? 'border-gold-500/20 text-sand-300' : 'border-slate-200/80 text-slate-600'
              }`}>
                <div className="flex items-start gap-1.5">
                  <Zap className={`w-3.5 h-3.5 shrink-0 mt-0.5 ${isDark ? 'text-gold-400' : 'text-amber-600'}`} />
                  <div>
                    <strong className={isDark ? 'text-gold-300' : 'text-navy-950'}>{t('memberships.qualification', 'Calificación:')} </strong>
                    <span className="text-[11px] leading-relaxed">{tier.qualification}</span>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Ultra-Modern Interactive Commission Simulator */}
      <div className="bg-white p-6 md:p-8 rounded-3xl border border-slate-200/90 shadow-sm relative overflow-hidden">
        <div className="flex items-center gap-3 mb-6 pb-4 border-b border-slate-100">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-amber-600 via-gold-500 to-amber-300 text-navy-950 flex items-center justify-center shadow-lg shadow-gold-500/25 ring-4 ring-amber-50">
            <Calculator className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-lg font-serif font-extrabold text-navy-950">
              {t('memberships.simulatorTitle', 'Simulador de Comisiones de Compra Multinivel')}
            </h3>
            <p className="text-xs text-slate-500 font-medium">
              {t('memberships.simulatorDesc', 'Pruebe cómo el motor de comisiones distribuye los puntos a la línea ascendente según el nivel de cada sponsor')}
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Controls */}
          <div className="space-y-4 bg-gradient-to-b from-slate-50 to-sand-50/60 p-6 rounded-2xl border border-slate-200 shadow-xs">
            <div>
              <label className="block text-[11px] font-extrabold uppercase tracking-wider text-navy-900 mb-1.5">
                {t('memberships.simPackagePoints', 'Puntos del Paquete Comprado (PTS)')}
              </label>
              <div className="relative">
                <input
                  type="number"
                  min="1"
                  value={simulationPoints}
                  onChange={(e) => setSimulationPoints(Math.max(0, Number(e.target.value)))}
                  className="w-full px-4 py-2.5 text-base font-black bg-white border border-slate-300 rounded-xl focus:border-gold-500 outline-none ring-0 focus:outline-none focus:ring-0 font-mono text-navy-950 transition-colors"
                />
                <span className="absolute right-3.5 top-2.5 text-xs font-black text-slate-400 font-mono">
                  PTS
                </span>
              </div>
            </div>

            <div>
              <CustomSelect
                label={t('memberships.simL1Tier', 'Membresía Patrocinador Directo (N1)')}
                value={simL1Tier}
                onChange={(e) => setSimL1Tier(e.target.value)}
                options={[
                  { value: 'member', label: isEn ? 'Member (0%)' : 'Miembro (0%)' },
                  { value: 'active_member', label: isEn ? 'Active Member (100%)' : 'Miembro Activo (100%)' },
                  { value: 'ambassador', label: isEn ? 'Ambassador (100%)' : 'Embajador (100%)' },
                  { value: 'elite_ambassador', label: isEn ? 'Elite Ambassador (100%)' : 'Embajador Élite (100%)' },
                ]}
              />
            </div>

            <div>
              <CustomSelect
                label={t('memberships.simL2Tier', 'Membresía Patrocinador Superior (N2)')}
                value={simL2Tier}
                onChange={(e) => setSimL2Tier(e.target.value)}
                options={[
                  { value: 'member', label: isEn ? 'Member (0%)' : 'Miembro (0%)' },
                  { value: 'active_member', label: isEn ? 'Active Member (0%)' : 'Miembro Activo (0%)' },
                  { value: 'ambassador', label: isEn ? 'Ambassador (50%)' : 'Embajador (50%)' },
                  { value: 'elite_ambassador', label: isEn ? 'Elite Ambassador (50%)' : 'Embajador Élite (50%)' },
                ]}
              />
            </div>
          </div>

          {/* Results Flow */}
          <div className="lg:col-span-2 flex flex-col justify-between space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {/* Buyer */}
              <div className="p-5 rounded-2xl bg-gradient-to-b from-white to-slate-50 border border-slate-200 shadow-xs">
                <span className="text-[10px] uppercase font-extrabold tracking-wider text-slate-500 block mb-1">
                  {t('memberships.simBuyer', 'Comprador')}
                </span>
                <p className="text-sm font-black text-navy-950">{isEn ? 'Member' : 'Miembro'}</p>
                <p className="text-2xl font-serif font-extrabold text-navy-950 mt-2 font-mono">
                  {simulationPoints} <span className="text-xs font-sans text-slate-400">PTS</span>
                </p>
                <p className="text-[11px] text-emerald-700 font-bold mt-2 flex items-center gap-1">
                  <TrendingUp className="w-3.5 h-3.5" />
                  <span>{isEn ? 'Qualifies for Active' : 'Califica para Activo'}</span>
                </p>
              </div>

              {/* L1 Sponsor */}
              <div className="p-5 rounded-2xl bg-gradient-to-b from-amber-50/60 to-white border border-amber-200 shadow-xs">
                <span className="text-[10px] uppercase font-extrabold tracking-wider text-amber-900 block mb-1">
                  {t('memberships.simL1Sponsor', 'Patrocinador Directo (N1)')}
                </span>
                <p className="text-sm font-black text-navy-950 capitalize">{simL1Tier.replace('_', ' ')}</p>
                <p className="text-2xl font-serif font-extrabold text-amber-700 mt-2 font-mono">
                  +{l1Earned} <span className="text-xs font-sans text-amber-600 font-bold">PTS</span>
                </p>
                <p className="text-[11px] text-slate-600 font-medium mt-2">
                  {t('points.appliedRate', 'Tasa')}: <strong className="text-navy-950 font-mono">{getTierRate(simL1Tier, 1) * 100}%</strong>
                </p>
              </div>

              {/* L2 Sponsor */}
              <div className="p-5 rounded-2xl bg-gradient-to-b from-sky-50/60 to-white border border-sky-200 shadow-xs">
                <span className="text-[10px] uppercase font-extrabold tracking-wider text-sky-900 block mb-1">
                  {t('memberships.simL2Sponsor', 'Patrocinador Indirecto (N2)')}
                </span>
                <p className="text-sm font-black text-navy-950 capitalize">{simL2Tier.replace('_', ' ')}</p>
                <p className="text-2xl font-serif font-extrabold text-sky-700 mt-2 font-mono">
                  +{l2Earned} <span className="text-xs font-sans text-sky-600 font-bold">PTS</span>
                </p>
                <p className="text-[11px] text-slate-600 font-medium mt-2">
                  {t('points.appliedRate', 'Tasa')}: <strong className="text-navy-950 font-mono">{getTierRate(simL2Tier, 2) * 100}%</strong>
                </p>
              </div>
            </div>

            {/* Total Issued Banner */}
            <div className="p-5 rounded-2xl bg-gradient-to-r from-navy-950 via-[#23140C] to-navy-950 text-white flex items-center justify-between border border-gold-500/30 shadow-lg shadow-navy-950/20">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-gold-500/20 text-gold-400 flex items-center justify-center border border-gold-500/30">
                  <Coins className="w-5 h-5" />
                </div>
                <div>
                  <p className="text-sm font-serif font-bold text-gold-400">
                    {t('memberships.simTotalDistributed', 'Total Puntos de Comisión Emitidos')}
                  </p>
                  <p className="text-xs text-sand-300/80 font-medium">
                    {t('memberships.simTotalSum', 'Suma distribuida a patrocinadores L1 y L2')}
                  </p>
                </div>
              </div>
              <span className="text-3xl font-serif font-black text-transparent bg-clip-text bg-gradient-to-r from-gold-300 via-gold-400 to-amber-200 font-mono">
                {l1Earned + l2Earned} PTS
              </span>
            </div>
          </div>
        </div>
      </div>
    </AdminShell>
  );
}
